/**:
  ros__parameters:
    # Lidar 설정
    use_lidar: false
    # QoS 설정
    input_qos: "SENSOR_DATA"
    # 맵 클리어링 설정
    map_clearing_frame_id: "zed_camera_link"
    # map_clearing_radius_m: -1.0 # no map clearing if < 0.0
    # Rviz 시각화
    slice_visualization_attachment_frame_id: "zed_camera_link"
   
    static_mapper:
      esdf_slice_height: 0.0
      esdf_slice_min_height: -0.1
      esdf_slice_max_height: 0.3

    dynamic_mapper:
      esdf_slice_height: 0.0
      esdf_slice_min_height: -0.1
      esdf_slice_max_height: 0.3

    