# /**:
#   ros__parameters:
#     # Lidar 설정
#     use_lidar: false
#     # QoS 설정
#     input_qos: "SENSOR_DATA"
#     # 맵 클리어링 설정
#     map_clearing_frame_id: "zed_camera_center"
#     # Rviz 시각화
#     slice_visualization_attachment_frame_id: "zed_camera_center"

#     # static_mapper:
#     #   esdf_slice_height: 0.0
#     #   esdf_slice_min_height: -0.1
#     #   esdf_slice_max_height: 0.3

#     dynamic_mapper:
#       esdf_slice_height: 0.0
#       esdf_slice_min_height: -0.1
#       esdf_slice_max_height: 0.3

#     static_mapper:
#       # mapper
#       maintain_mesh_block_stream_queue: true
#       do_depth_preprocessing: false
#       depth_preprocessing_num_dilations: 3
#       # projective integrator (tsdf/color/occupancy)
#       projective_integrator_max_integration_distance_m: 5.0
#       projective_integrator_truncation_distance_vox: 4.0
#       projective_integrator_weighting_mode: "inverse_square_tsdf_distance_penalty"
#       projective_integrator_max_weight: 5.0
#       # occupancy integrator
#       free_region_occupancy_probability: 0.45
#       occupied_region_occupancy_probability: 0.55
#       unobserved_region_occupancy_probability: 0.5
#       occupied_region_half_width_m: 0.1
#       # esdf integrator
#       esdf_integrator_min_weight: 0.1
#       esdf_integrator_max_site_distance_vox: 5.0
#       esdf_integrator_max_distance_m: 2.0
#       # mesh integrator
#       mesh_integrator_min_weight: 0.1
#       mesh_integrator_weld_vertices: true
#       # tsdf decay integrator
#       tsdf_decay_factor: 0.95
#       exclude_last_view_from_decay: true
#       # mesh streamer
#       mesh_streamer_exclusion_height_m: 2.0
#       mesh_streamer_exclusion_radius_m: 7.0
#       mesh_bandwidth_limit_mbps: 999999925.0 # in mega bits per second
#       # freespace integrator
#       max_tsdf_distance_for_occupancy_m: 0.15
#       max_unobserved_to_keep_consecutive_occupancy_ms: 200
#       min_duration_since_occupied_for_freespace_ms: 250
#       min_consecutive_occupancy_duration_for_reset_ms: 2000
#       check_neighborhood: true

#########################

# /**:
#   ros__parameters:
#     # Lidar 설정
#     use_lidar: false
#     # QoS 설정
#     input_qos: "SENSOR_DATA"
#     # 맵 클리어링 설정
#     # map_clearing_frame_id: "zed_camera_center"
#     # map_clearing_frame_id: "map"
#     # Rviz 시각화
#     # slice_visualization_attachment_frame_id: "zed_camera_center"
#     # slice_visualization_side_length: 100.0

#     # 매핑 타입 설정: static_occupancy 또는 dynamic_occupancy 중 선택
#     mapping_type: static_occupancy  # 또는 dynamic_occupancy  이거 때문에 코스트맵 남아 있는거 같음. 검증필요

#     # Voxel 크기 설정
#     voxel_size: 0.03

#     # Occupancy 레이어 퍼블리싱 활성화
#     publish_occupancy_layer: true

#     # ESDF 슬라이스 설정 (static 및 dynamic mapper에 대해 설정)
#     static_mapper:
#       esdf_slice_height: 0.0
#       esdf_slice_min_height: -0.1
#       esdf_slice_max_height: 0.3

#     dynamic_mapper:
#       esdf_slice_height: 0.0
#       esdf_slice_min_height: -0.1
#       esdf_slice_max_height: 0.3

#     # Occupancy 레이어 시각화 설정
#     # layer_visualization_max_tsdf_distance_m: 2.0
#     # layer_visualization_min_tsdf_weight: 1.0
#     # layer_visualization_exclusion_height_m: 0.5
#     # layer_visualization_exclusion_radius_m: 5.0

#     layer_visualization_max_tsdf_distance_m: 5.0
#     layer_visualization_min_tsdf_weight: 1.0
#     layer_visualization_exclusion_height_m: 0.5
#     layer_visualization_exclusion_radius_m: 5.0

#     # Occupancy 레이어 퍼블리싱 주기 (옵션)
#     publish_layer_rate_hz: 10.0

#     # ESDF 퍼블리싱 주기 (옵션)
#     update_esdf_rate_hz: 10.0





/**:
  ros__parameters:
    # Lidar 설정
    use_lidar: false
    # QoS 설정
    input_qos: "SENSOR_DATA"

    # 맵 클리어링 설정 -> 이놈이 esdf 데이터 지속적으로 사라지게 하는 녀석
    # 지금은 nvblox_node_params.hpp 에서 맵 클리어링 프레임 id가 "map"으로 설정되어있어서 안 없어짐
    # 없어지게 바꾸고 싶다? -> 맵 클리어링 id를 카메라 프레임 넣으면됨

    # map_clearing_frame_id: "zed_camera_center"
    # map_clearing_radius_m: -1.0 # no map clearing if < 0.0
    # Rviz 시각화
    slice_visualization_attachment_frame_id: "zed_camera_center"

    # 매핑 타입 설정: static_occupancy 또는 dynamic_occupancy 중 선택
    mapping_type: static_occupancy  # 또는 dynamic_occupancy  이거 때문에 코스트맵 남아 있는거 같음. 검증필요

    # Voxel 크기 설정
    voxel_size: 0.03

    # Occupancy 레이어 퍼블리싱 활성화
    publish_occupancy_layer: true
    
   
    static_mapper:
      esdf_slice_height: 0.0
      esdf_slice_min_height: -0.1
      esdf_slice_max_height: 0.3

    dynamic_mapper:
      esdf_slice_height: 0.0
      esdf_slice_min_height: -0.1
      esdf_slice_max_height: 0.3